<?php

return [
    'categories' => [
        ['id' => 1, 'label' => 'Activism and NGOs'],
        ['id' => 2, 'label' => 'Animals'],
        ['id' => 3, 'label' => 'Beauty'],
        ['id' => 4, 'label' => 'Celebrities'],
        ['id' => 5, 'label' => 'Cinema and TV'],
        ['id' => 6, 'label' => 'Computer and Programming'],
        ['id' => 7, 'label' => 'Construction and Renovations'],
        ['id' => 8, 'label' => 'Cooking, Recipes and Gastronomy'],
        ['id' => 9, 'label' => 'Curiosities'],
        ['id' => 10, 'label' => 'Dating'],
        ['id' => 11, 'label' => 'Decoration and DIY'],
        ['id' => 12, 'label' => 'Economy'],
        ['id' => 13, 'label' => 'Education and Formation'],
        ['id' => 14, 'label' => 'Entrepreneurs and SME'],
        ['id' => 15, 'label' => 'Erotic and Sex'],
        ['id' => 16, 'label' => 'Esoteric and Paranormal'],
        ['id' => 17, 'label' => 'Fashion and Accessories'],
        ['id' => 18, 'label' => 'Gambling, Casino and Sweepstakes'],
        ['id' => 19, 'label' => 'Games'],
        ['id' => 20, 'label' => 'Health'],
        ['id' => 21, 'label' => 'House and Garden'],
        ['id' => 22, 'label' => 'Humorous'],
        ['id' => 23, 'label' => 'Insurances'],
        ['id' => 24, 'label' => 'Legal'],
        ['id' => 25, 'label' => 'Leisure'],
        ['id' => 26, 'label' => 'Loans'],
        ['id' => 27, 'label' => 'Marriage and Family'],
        ['id' => 28, 'label' => 'Motivation and Inspiration'],
        ['id' => 29, 'label' => 'News'],
        ['id' => 30, 'label' => 'Real Estate'],
        ['id' => 31, 'label' => 'Science and Technology'],
        ['id' => 32, 'label' => 'Sports'],
        ['id' => 33, 'label' => 'Tourism'],
        ['id' => 34, 'label' => 'Transport'],
        ['id' => 35, 'label' => 'Weddings'],
    ],
];
